id: P000510
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:43:40.545308
source_metadata:
  id: bdr:W4CZ74475
  title: སྐུ་འབུམ་གདན་རབས།
  author: ''
  volumes:
    948806c15642406ba46c2ced3e4498e2:
      image_group_id: I2PD18102
      title: Volume 1 of dpe war mchog sprul 'jam dbyangs bsod nams dbang po'i gsan
        yig 'dod rgu'i bang mdzod/
      volume_number: 1
      total_pages: 594
    d0bcdced0d444045bdd38523145cf077:
      image_group_id: I2PD18103
      title: Volume 2 of dpe war mchog sprul 'jam dbyangs bsod nams dbang po'i gsan
        yig 'dod rgu'i bang mdzod/
      volume_number: 2
      total_pages: 506
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
